### ISSUE TITLE
Investigate why the Debug Agent generates an exception trace when running test with expected exception.

### ISSUE THREAD

**Issue by qasimy123** [r30shah/openj9-jit-debug-agent#7] opened 2021-10-15 00:23 UTC
### Steps to reproduce
1. Ensure Debug Agent is enabled in JVM. i.e replace the following lines in reflect/Method.invoke
```java 
return ma.invoke(obj, args);
```
with 
```java 
return com.ibm.jit.JITHelpers.invoke(ma, obj, args);
```

2. Ensure the artificial "bug" is disabled.
```console
unset TR_DebugAgentBug
```

3. Change test_Constructor13 in Test_String.java to 
```java
/**
* @tests java.lang.String#String(java.lang.String)
*/
@Test(expected = NullPointerException.class)
public void test_Constructor13() {
   throw new NullPointerException();
}
```
Recompile with
```console
/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/jdk/bin/javac -cp ./junit-4.12.jar DebugAgentRunner.java Test_String.java
```

Run the test 
```console
/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/jdk/bin/java -Xdump:none -Xnoaot -Xcheck:jni -Xjit:forceUsePreexistence -cp ./junit-4.12.jar:./hamcrest-all-1.3.jar:. DebugAgentRunner 20000 &> trace.txt
```
I obtain the following output
[trace.txt](https://github.com/r30shah/openj9-jit-debug-agent/files/7350005/trace.txt)

**Comment by r30shah** [comment] 2021-11-02 14:13
I was able to reproduce this and find the cause of the failure. When we call a clean-up function `debugAgentEnd` we need to suspend diagnostic thread as well, as we were not doing that, the diagnostic thread was trying to compile when we exit the JVM. 
https://github.com/r30shah/openj9-jit-debug-agent/commit/18c7a5dc1f9e031c50ff98d45b8164b9e6bbabd2 should fix the issue.

**Comment by r30shah** [comment] 2021-11-30 15:19
Closing this issue as it was fixed by https://github.com/r30shah/openj9-jit-debug-agent/commit/18c7a5dc1f9e031c50ff98d45b8164b9e6bbabd2

**Closed as completed by r30shah** 2021-11-30 15:19 UTC
